-- SELECIONANDO TODOS OS REGISTROS DA TABELA DE ALUNOS
SELECT * FROM tbl_alunos;

-- SELECTIONANDO TODOS OS REGISTROS DA TABELA DE CIDADES
SELECT * FROM tbl_cidades;

-- SELEÇÃO DE TESTE COM ALUNOS E CIDADES, MAS PRIORIZANDO OS REGISTROS DOS ALUNOS
SELECT * FROM tbl_alunos 
LEFT JOIN tbl_cidades 
ON tbl_alunos.Id_Cidade = tbl_cidades.Id_Cidade;

-- SELEÇÃO DE TESTE COM ALUNOS E CIDADES NA INTERSECÇÃO DE AMBAS TABELAS (EXCLUI OS 'NULL'S)
SELECT * FROM tbl_alunos 
INNER JOIN tbl_cidades 
ON tbl_alunos.Id_Cidade = tbl_cidades.Id_Cidade;